"""create all tables + support

Revision ID: 2288e91de761
Revises: 4fb83edd5019
Create Date: 2025-11-24 11:32:41.053219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2288e91de761'
down_revision = '4fb83edd5019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
