"""add support ticket and messages

Revision ID: 7e2e88b3ebac
Revises: 2288e91de761
Create Date: 2025-11-24 12:04:20.520796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e2e88b3ebac'
down_revision = '2288e91de761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
